Style tweaks
AIObjectives/talk-to-the-city-reports pull request #24
Opened 2023-11-13 07:28 UTC by colleenm

2023-11-13 07:36 UTC, colleenm commented
note: in Report.tsx, lines 82 (main) and 59 (this branch) don't actually correspond, I haven't changed the target for setOpenMap() -- git diff is just confused by new indents from the wrapper <div> that makes the two-column layout work

2023-11-15 18:06 UTC, colleenm commented
@Onurbon Screenshots added to PR description

2023-11-15 20:16 UTC, Onurbon requested changes
See comment on using tailwind theme (I would prefer to avoid manual overrides of tailwind classes), but otherwise all good!

2023-11-15 20:16 UTC, Onurbon commented on next-app/components/Outline.tsx
> +  return <div className='hidden lg:block sticky left-0 top-10 pr-4 pl-4 text-left
why sticky instead of fixed?

2023-11-15 20:16 UTC, Onurbon commented on next-app/globals.css
> +
I think the proper tailwind way to do this is by extending the default theme as per https://tailwindcss.com/docs/theme

Could you try adding something like the following on in your tailwind config? 

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      text: {
       'xl': '1.25rem'
        '3xl': '2rem'
      }
    }
  }
}
```

2023-11-15 20:16 UTC, Onurbon commented on next-app/hooks/useClusterColor.ts
> +  "#4169e1", // Royal Blue
Thank you so much for improving the colors! 🙏 
The list I had put there was generated with chatpgt and it wasn't great.

2024-04-21 23:13 UTC, lightningorb commented
Closing as this is now outdated.

2024-04-21 23:13 UTC, closed without merging